### ISSUE TITLE
luz-next_performer error

### ISSUE THREAD

**Issue by Giladx** [lighttroupe/luz#11]
While I am trying to run it I get 

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- sdl_application (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ./luz_performer.rb:6:in `<main>'
```

what do I need to gem ?
Ubuntu Mate 14.04 

thanx

**Comment by lighttroupe** [comment]
sdl_application.rb is in the utils directory.

Are you running Luz from its root directory?

I recommend you cd into the directory and do:
ruby luz.rb --system-mouse --window

(and then use a window manager key to go fullscreen, which you can configure in System / Preferences / Keyboard Shortcuts option "Toggle maximization state", and I personally set it to Ctrl-F11)

**Comment by lighttroupe** [comment]
Tons of changes in an update to sdl2 and ubuntu 15.04.

The docs are updated with minimal steps to get things working.
