### ISSUE TITLE
Problems to run Luz-Next in Ubuntu Studio 16.04

### ISSUE THREAD

**Issue by diegomadero** [lighttroupe/luz#12]
Hello

Since I upgraded to Ubuntu Studio 16.04 (from 14.04), I failed to run Luz-Next :(

First I had to use RVM to install and switch to Ruby-2.1.-full1 because with the current Ruby version, sends an error message about the version of Ruby:

`For Speed and Smoooth Flow, choose Ruby Version 2.1 (you are using 2.3.0)`

By changing the version I no longer get that error, but I get this other one. I tryed reinstalling and with some other sub-versions of the 2.1

```
   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.1 [ x86_64 ]
=* ruby-2.1.1-full [ x86_64 ]
   ruby-2.1.4 [ x86_64 ]
   ruby-2.3.0-full [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

...but I always get the same error:

```
Using Ruby 2.1.1
/home/dm/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require ': can not load such file - sdl2 (LoadError )
/home/dm/.rvm/rubies/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in from `require '
/home/dm/luz-next/utils/reloadable_require.rb:21:in from `block in multi_require '
`/home/dm/luz-next/utils/reloadable_require.rb:20:in from each '
`/home/dm/luz-next/utils/reloadable_require.rb:20:in from multi_require '
from luz.rb: 23: in `<main> '
```

Is it a compatibility issue? Or will there be any way to fix it?

Thanks!

**Comment by lighttroupe** [comment]
Hi Diego!
I just pushed a change to make it work with any Ruby 2.
The other error seems to be "can not load sdl2" so you'll need to get that installed for the version of Ruby you're using.
-Ian
