### ISSUE TITLE
window resolution problems

### ISSUE THREAD

**Issue by irinea** [lighttroupe/luz#13]
I have just installed Luz Next in Ubuntu Studio 16.04
I am not sure if it is a resolution problem but the elements inside the window can't seem to fit, so mouse clicks are imprecise and the plus symbol for adding new effects to an element does not work, I can't access the title bar of the window nor the minimize/maximize buttons. Also, I can't run the spectrum analyzer :/

![luzscreen](https://cloud.githubusercontent.com/assets/22599155/19047896/79dac5a6-8969-11e6-9a13-b12dffa38799.png)

this is how it looks

**Comment by lighttroupe** [comment]
Luz 2 is meant to be run fullscreen.

I personally run it as "ruby luz.rb --system-mouse --window" and then use a
system keyboard shortcut Ctrl-F11 to go fullscreen (you might have to
configure that yourself outside Luz)..

But you can also run it without --window, and it just won't be as easy to
go in/out of Luz.

**Comment by irinea** [comment]
Great, thanks!
