### ISSUE TITLE
Installing Luz 2 on linux 18.04

### ISSUE THREAD

**Issue by burcugunduz** [lighttroupe/luz#14]
Hi
I appreciate what you have done!! seems fantastic:) I will be very happy if i could install it properly (i am a vj from istanbul).
What is the correct comment after **cd luz**
vjunk@vjunk-HP-ProBook-4525s:~$ cd luz
vjunk@vjunk-HP-ProBook-4525s:~/luz$ ./build.sh utils/webcam
bash: ./build.sh: No such file or directory

Can you please help?

**Comment by lighttroupe** [comment]
I recommend you get Luz running first, before building webcam / video-file plugins.

To build them, first cd into the directory:
cd utils/webcam
./build.sh
