### ISSUE TITLE
Cwiimote no longer exists

### ISSUE THREAD

**Issue by tedr56** [lighttroupe/luz#2]
The new library name is libcwiid.

**Comment by lighttroupe** [comment]
input-manager has been updated to use the new libcwiid library.

It currently only supports buttons (not pitch / roll / yaw), but I'm closing this bug as it compiles and a wiimote as a wireless remote control is still pretty darn useful.

Help is wanted calculating really good pitch/roll/yaw from the raw wiimote data.
