### ISSUE TITLE
In/Out Curves doesn't disappear after curve change

### ISSUE THREAD

**Issue by tedr56** [lighttroupe/luz#5]
At least on Primitive's FX

**Comment by lighttroupe** [comment]
This was perhaps the only real 'bug' in the custom user interface of Luz 2.  Never fixed.

Work has moved to Luz 3, built from scratch on the Godot game engine for easy portability to Linux, OSX, Windows, and more.  And VR support.  And is now fully 3D.  Will be released soon.

![Screenshot from 2024-04-07 23-42-10](https://github.com/lighttroupe/luz/assets/1422772/6b601314-880c-45bd-9aaf-761f6fea45e5)
