### ISSUE TITLE
cannot build utils/video_file

### ISSUE THREAD

**Issue by rhetr** [lighttroupe/luz#7]
when I run ./build on utils/video_file I receive the following error:

Building ffmpeg for Ruby 1.9...
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby1.9.1
    --with-ffmpeg-dir
    --without-ffmpeg-dir
    --with-ffmpeg-include
    --without-ffmpeg-include=${ffmpeg-dir}/include
    --with-ffmpeg-lib
    --without-ffmpeg-lib=${ffmpeg-dir}/lib
    --with-avformatlib
    --without-avformatlib
extconf.rb:10:in `<main>': Missing needed development libraries (avformat, swscale). (RuntimeError)
make: *** No rule to make target`clean'.  Stop.
make: **\* No targets specified and no makefile found.  Stop.
/usr/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - ffmpeg.so (Errno::ENOENT)
    from /usr/lib/ruby/1.9.1/fileutils.rb:1515:in`block in fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
    from /usr/lib/ruby/1.9.1/fileutils.rb:1513:in`fu_each_src_dest'
    from /usr/lib/ruby/1.9.1/fileutils.rb:508:in `mv'
    from ./build:14:in`<main>'

i searched my installed software and already have both libavformat-dev and libswscale-dev. ubuntu and a few other distros use avconv instead of ffmpeg. is that the problem?

**Comment by lighttroupe** [comment]
I recently got video_file support working on Ubuntu 15.04 on the sdl2 branch.

Could you give it a try on the sdl2 branch?

**Comment by lighttroupe** [comment]
Video file plugin should be working again (at least in ubuntu 15.04).  Try the new build.sh
